apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflows
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: airflow
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/apache/airflow.git
    targetRevision: 1.8.0-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
